### ISSUE TITLE
Automatically generate Python wrappers for V11 library

### ISSUE THREAD

**Issue by tommymchugh** [InclusiveTechNU/v11#12]
Currently, V11 is planning on implementing wrappers for the C++ library particularly to support Python applications being developed at the ITL lab.

Ideally we would like to have these wrappers be generated automatically for Python. If we can generate the library for more than just Python that would be awesome, but Python is of most importance. Other langs that could be important

- Java/C#/Kotlin
- Swift
- Go
- Dart
- Racket (not of importance but could be a cool way to introduce in CS 111)
- Rust
- Block-based langs like Scratch would be awesome

**Tools that could help implement:**  [Swig](http://www.swig.org/)

**Comment by tommymchugh** [comment]
Some resources to help:

https://swig.org
https://github.com/rust-lang/rust-bindgen

and .... just for funzees
https://docs.racket-lang.org/dynamic-ffi/index.html

**Comment by cooperbarth** [comment]
C#, Go, Java, Python, and Ruby bindings added. Looking into Rust.
