### ISSUE TITLE
REPL - Exits on error

### ISSUE THREAD

**Issue by tommymchugh** [InclusiveTechNU/v11#16]
V11 REPL will quit when an error occurs

**Expected behavior:** Error is displayed and the user can run another command.

**Comment by cooperbarth** [comment]
https://github.com/InclusiveTechNU/v11/pull/22

**Comment by tommymchugh** [comment]
Thanks for taking that on

**Comment by cooperbarth** [comment]
Reopened because of inconsistent behavior - some errors (such as "const test = " aren't handled)

**Comment by cooperbarth** [comment]
fixed in https://github.com/InclusiveTechNU/v11/pull/23
